extends: terminal-dark

block_quote:
  colors:
    background: "1d0f0f"

execution_output:
  colors:
    background: "2d2d2d"

inline_code:
  colors:
    background: "2d2d2d"

footer:
  style: template
  left: "{author}"
  right: "{current_slide} / {total_slides}"
  colors:
    foreground: green
