### Eval
eval:
  figlet:
    command: figlet 
    replace: true
    fragment: false
    container: none
  haskell:
    command: runhaskell -w

### Look & Feel
images:
  backend: auto
incrementalLists: true
margins:
  left: auto
  right: auto
  top: auto
slidelevel: 2
theme:
  borders: [vividGreen]
  codeBlock: [onRgb#1c1c1c]
  code: [onRgb#1c1c1c]
  emph: [dullYellow]
  header: [vividBlue]
  strong: [vividMagenta, bold]
#  syntaxHighlighting:
#    keyword: [rgb#9CDC1E]
#    dataType: [rgb#569CD6]
  title: [vividBlue]
wrap: true
