---
# yaml-language-server: $schema=https://raw.githubusercontent.com/mfontanini/presenterm/master/config-file-schema.json
defaults:
  # the theme to use by default in every presentation unless overridden.
  theme: terminal-dark-custom

typst:
  # the pixels per inch when rendering latex/typst formulas.
  ppi: 400

snippet:
  exec:
    # enable code snippet execution. Use at your own risk!
    enable: true

  render:
    # the number of threads to use when rendering `+render` code snippets.
    threads: 8

bindings:
  # the keys that cause the presentation to move forwards.
  next: ["l", "j", "<right>", "<page_down>", "<down>", " "]

  # the keys that cause the presentation to move forwards fast.
  next_fast: ["n"]

  # the keys that cause the presentation to move backwards.
  previous: ["h", "k", "<left>", "<page_up>", "<up>"]

  # the keys that cause the presentation to move backwards fast
  previous_fast: ["p"]

  # the key binding to jump to the first slide.
  first_slide: ["gg"]

  # the key binding to jump to the last slide.
  last_slide: ["G"]

  # the key binding to jump to a specific slide.
  go_to_slide: ["<number>G"]

  # the key binding to execute a piece of shell code.
  execute_code: ["."]

  # the key binding to reload the presentation.
  reload: ["<F5>","<esc>"]

  # the key binding to toggle the slide index modal.
  toggle_slide_index: ["<c-p>"]

  # the key binding to toggle the key bindings modal.
  toggle_bindings: ["?"]

  # the key binding to close the currently open modal.
  close_modal: ["`"]

  # the key binding to close the application.
  exit: ["<c-c>", "q"]

  # the key binding to suspend the application.
  suspend: ["<c-z>"]
